version: "3.8"

services:
    postgres:
        image: postgres:13.2-alpine
        container_name: postgres_13
        restart: always
        network_mode: network_bd
        ports:
            - 5435:5432
        
        volumes: 
            - /opt/postgres/config/postgresql.conf:/usr/local/share/postgresql/postgresql.conf
            - /opt/postgres/data:/var/lib/postgresql/data
            - /opt/shared_container:/tmp
        environment:
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: desarrollos

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        restart: always
        network_mode: network_bd
        ports:
            - 5050:80

        environment: 
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret


volumes:
    postgres.conf: {}
    data: {}
    shared_container: {}    